const ingredientAliases = {
  "abobrinha": [ "abobrinha", "zucchini", "calabacín", "courgette" ],
  "acucar": [ "acucar", "açúcar", "sugar", "azúcar", "sucre" ],
  "alecrim": [ "alecrim", "rosemary", "romero", "romarin" ],
  "alface": [ "alface", "lettuce", "lechuga", "laitue" ],
  "alho": [ "alho", "garlic", "ajo", "ail" ],
  "arroz": [ "arroz", "rice", "arroz", "riz" ],
  "atum": [ "atum", "tuna", "atún", "thon" ],
  "aveia": [ "aveia", "oats", "avena", "avoine" ],
  "azeite": [ "azeite", "olive oil", "aceite de oliva", "huile d'olive" ],
  "banana": [ "banana", "banana", "plátano", "banane" ],
  "berinjela": [ "berinjela", "eggplant", "berenjena", "aubergine" ],
  "beterraba": [ "beterraba", "beetroot", "remolacha", "betterave" ],
  "calabresa": [ "calabresa", "calabresa sausage", "chorizo calabresa", "saucisse calabresa" ],
  "caldo_de_carne": [ "caldo de carne", "beef broth", "caldo de carne", "bouillon de boeuf" ],
  "caldo_de_legumes": [ "caldo de legumes", "vegetable broth", "caldo de verduras", "bouillon de légumes" ],
  "carne_moida": [ "carne moída", "ground beef", "carne molida", "boeuf haché" ],
  "cebola": [ "cebola", "onion", "cebolla", "oignon" ],
  "cebola_roxa": [ "cebola roxa", "red onion", "cebolla morada", "oignon rouge" ],
  "cebolinha": [ "cebolinha", "chives", "cebollino", "ciboulette" ],
  "cenoura": [ "cenoura", "carrot", "zanahoria", "carotte" ],
  "champignon": [ "champignon", "mushroom", "champiñón", "champignon" ],
  "couve": [ "couve", "collard greens", "col rizada", "chou frisé" ],
  "coxa_de_frango": [ "coxa de frango", "chicken thigh", "muslo de pollo", "cuisse de poulet" ],
  "cravo_da_india": [ "cravo da índia", "clove", "clavo de olor", "clou de girofle" ],
  "creme_de_leite": [ "creme de leite", "cream", "nata", "crème" ],
  "espinafre": [ "espinafre", "spinach", "espinaca", "épinard" ],
  "farinha_de_rosca": [ "farinha de rosca", "breadcrumbs", "pan rallado", "chapelure" ],
  "farinha_de_trigo": [ "farinha de trigo", "wheat flour", "harina de trigo", "farine de blé" ],
  "feijao": [ "feijão", "bean", "frijol", "haricot" ],
  "fermento": [ "fermento", "yeast", "levadura", "levure" ],
  "frango_desfiado": [ "frango desfiado", "shredded chicken", "pollo desmenuzado", "poulet effiloché" ],
  "ketchup": [ "ketchup", "ketchup", "kétchup", "ketchup" ],
  "laranja": [ "laranja", "orange", "naranja", "orange" ],
  "leite": [ "leite", "milk", "leche", "lait" ],
  "leite_condensado": [ "leite condensado", "condensed milk", "leche condensada", "lait concentré" ],
  "limao": [ "limão", "lemon", "limón", "citron" ],
  "lombo_canadense": [ "lombo canadense", "canadian bacon", "lomo canadiense", "lard canadien" ],
  "louro": [ "louro", "bay leaf", "laurel", "laurier" ],
  "maca": [ "maçã", "apple", "manzana", "pomme" ],
  "maionese": [ "maionese", "mayonnaise", "mayonesa", "mayonnaise" ],
  "manjericao": [ "manjericão", "basil", "albahaca", "basilic" ],
  "manteiga": [ "manteiga", "butter", "mantequilla", "beurre" ],
  "milho": [ "milho", "corn", "maíz", "maïs" ],
  "molho_barbecue": [ "molho barbecue", "barbecue sauce", "salsa barbacoa", "sauce barbecue" ],
  "molho_de_tomate": [ "molho de tomate", "tomato sauce", "salsa de tomate", "sauce tomate" ],
  "molho_shoyu": [ "molho shoyu", "soy sauce", "salsa de soja", "sauce soja" ],
  "morango": [ "morango", "strawberry", "fresa", "fraise" ],
  "mostarda": [ "mostarda", "mustard", "mostaza", "moutarde" ],
  "nozes": [ "nozes", "walnut", "nuez", "noix" ],
  "noz_moscada": [ "noz-moscada", "nutmeg", "nuez moscada", "muscade" ],
  "oregano": [ "orégano", "oregano", "orégano", "origan" ],
  "ovo": [ "ovo", "egg", "huevo", "œuf" ],
  "ovo_frito": [ "ovo frito", "fried egg", "huevo frito", "œuf frit" ],
  "palmito": [ "palmito", "hearts of palm", "palmito", "cœur de palmier" ],
  "pao_de_forma": [ "pão de forma", "sliced bread", "pan de molde", "pain de mie" ],
  "pao_frances": [ "pão francês", "french bread", "pan francés", "baguette" ],
  "peito_de_peru": [ "peito de peru", "turkey breast", "pechuga de pavo", "blanc de dinde" ],
  "pimentao": [ "pimentão", "bell pepper", "pimiento", "poivron" ],
  "pimenta_calabresa": [ "pimenta calabresa", "crushed red pepper", "pimienta calabresa", "piment fort concassé" ],
  "pimenta_do_reino": [ "pimenta do reino", "black pepper", "pimienta negra", "poivre noir" ],
  "pimenta_vermelha": [ "pimenta vermelha", "red pepper", "pimiento rojo", "piment rouge" ],
  "presunto": [ "presunto", "ham", "jamón", "jambon" ],
  "queijo": [ "queijo", "cheese", "queso", "fromage", "mussarela", "mozzarella", "muzzarella", "muçarela", "mozarela","parmesao", "parmesan", "parmigiano", "parmesano", "parmesan","gorgonzola", "gorgonzola", "gorgonzola", "gorgonzola","provolone", "provolone", "provolone", "provolone","ricota", "ricotta", "ricotta", "ricotta", "ricotta" ],
  "rucula": [ "rúcula", "arugula", "rúcula", "roquette" ],
  "sal": [ "sal", "salt", "sal", "sel" ],
  "salsinha": [ "salsinha", "parsley", "perejil", "persil" ],
  "sardinha": [ "sardinha", "sardine", "sardina", "sardine" ],
  "tomate": [ "tomate", "tomato", "tomate", "tomate" ],
  "tomilho": [ "tomilho", "thyme", "tomillo", "thym" ],
  "vinagre": [ "vinagre", "vinegar", "vinagre", "vinaigre" ],
};