name: 'Check Pubspec Version'
description: 'Verifica se a versão no pubspec.yaml foi aumentada'

on:
  workflow_call:
    inputs:
      comparison_type:
        description: 'Tipo de comparação: "pr" (compara com main) ou "commit" (compara com commit anterior)'
        required: true
        type: string
      pubspec_path:
        description: 'Caminho para o arquivo pubspec.yaml'
        required: false
        type: string
        default: 'pubspec.yaml'

outputs:
  current_version:
    description: 'Versão atual do pubspec.yaml'
    value: ${{ steps.get-versions.outputs.current_version }}
  previous_version:
    description: 'Versão anterior (main ou commit anterior)'
    value: ${{ steps.get-versions.outputs.previous_version }}

runs:
  using: 'composite'
  steps:
    - name: Get versions and compare
      id: get-versions
      shell: bash
      run: |
        # Função para extrair versão do pubspec.yaml
        extract_version() {
          grep '^version:' "$1" | sed 's/version: //' | tr -d ' '
        }
        
        # Obtém versão atual
        CURRENT_VERSION=$(extract_version ${{ inputs.pubspec_path }})
        echo "current_version=$CURRENT_VERSION" >> $GITHUB_OUTPUT
        
        # Obtém versão anterior baseada no tipo de comparação
        if [ "${{ inputs.comparison_type }}" = "pr" ]; then
          # Para PR: compara com a versão na branch main
          git fetch origin main:main
          PREVIOUS_VERSION=$(git show main:${{ inputs.pubspec_path }} | extract_version /dev/stdin)
          COMPARISON_TEXT="branch main"
        elif [ "${{ inputs.comparison_type }}" = "commit" ]; then
          # Para push: compara com o commit anterior
          git fetch --unshallow || git fetch --depth=2
          PREVIOUS_VERSION=$(git show HEAD~1:${{ inputs.pubspec_path }} | extract_version /dev/stdin)
          COMPARISON_TEXT="commit anterior"
        else
          echo "❌ Tipo de comparação inválido: ${{ inputs.comparison_type }}"
          exit 1
        fi
        
        echo "previous_version=$PREVIOUS_VERSION" >> $GITHUB_OUTPUT
        
        # Exibe as versões
        echo "📋 Versão atual: $CURRENT_VERSION"
        echo "📋 Versão $COMPARISON_TEXT: $PREVIOUS_VERSION"
        
        # Verifica se a versão foi aumentada
        if [ "$CURRENT_VERSION" = "$PREVIOUS_VERSION" ]; then
          echo "❌ Versão não foi aumentada em relação ao $COMPARISON_TEXT"
          echo "   Versão atual: $CURRENT_VERSION"
          echo "   Versão $COMPARISON_TEXT: $PREVIOUS_VERSION"
          exit 1
        else
          echo "✅ Versão aumentada de $PREVIOUS_VERSION para $CURRENT_VERSION"
        fi
