name: Github Release

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: Build Android Application
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.13.9"
          channel: 'stable'
          cache: 'true'

      - name: Setup pub credentials
        run: echo '${{ secrets.PUB_CREDENTIALS }}' > ~/.pub-cache/credentials.json

      - name: Debug credentials file content
        run: cat ~/.pub-cache/credentials.json | jq .


      - name: Get dependencies
        run: flutter pub get

      - name: Publish package
        run: flutter pub publish --force
      #  env:
       #   PUB_TOKEN: ${{ secrets.PUB_CREDENTIALS }} 

      
