name: Github Release

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: Build Android Application
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4      
      
      - name: Check if pubspec.yaml version was increased
        if: github.event_name == 'pull_request'
        run: |
          git fetch origin main:main
          PREVIOUS_VERSION=$(grep '^version:' pubspec.yaml | sed 's/version: //')
          PREVIOUS_VERSION_MAIN=$(git show main:pubspec.yaml | grep '^version:' | sed 's/version: //')
          if [ "$PREVIOUS_VERSION" == "$PREVIOUS_VERSION_MAIN" ]; then
            echo "Version was not increased. Failing the workflow."
            exit 1
          fi

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.13.9"
          channel: 'stable'
          cache: 'true'

      - name: Ensure pub-cache directory exists
        run: mkdir -p $HOME/.config/dart
      
      - name: Save credentials.json
        run: echo '${{ secrets.PUB_CREDENTIALS }}' > $HOME/.config/dart/pub-credentials.json

      # Opcional, mas recomendado para cobrir todas as bases:
      - name: Create legacy .pub-cache directory
        run: mkdir -p $HOME/.pub-cache

      - name: Write pub credentials to legacy path
        run: echo '${{ secrets.PUB_CREDENTIALS }}' > $HOME/.pub-cache/credentials.json

      - name: Get dependencies
        run: flutter pub get

      - name: Publish package
        run: flutter pub publish --force
      #  env:
       #   PUB_TOKEN: ${{ secrets.PUB_CREDENTIALS }} 

      
