name: Github Release
description: 'Publica o pacote Flutter no pub.dev quando a versão é aumentada'

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  validate:
    name: Validate pubspec version
    uses: ./.github/workflows/check-pubspec-version.yml
    with:
      comparison_type: ${{ github.event_name == 'pull_request' && 'pr' || 'commit' }} # Indica se é um Pull Request ou Push na branch que disparou esse evento

  publish:
    name: Publish to pub.dev
    runs-on: ubuntu-latest
    needs: validate
    if: github.event_name == 'push' && github.ref == 'refs/heads/main' # só executa quando subir código na branch main

    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.13.9"
          channel: 'stable'
          cache: 'true'

      - name: Ensure pub-cache directory exists
        run: mkdir -p $HOME/.config/dart
      
      - name: Save credentials.json
        run: echo '${{ secrets.PUB_CREDENTIALS }}' > $HOME/.config/dart/pub-credentials.json

      # Opcional, mas recomendado para cobrir todas as bases:
      - name: Create legacy .pub-cache directory
        run: mkdir -p $HOME/.pub-cache

      - name: Write pub credentials to legacy path
        run: echo '${{ secrets.PUB_CREDENTIALS }}' > $HOME/.pub-cache/credentials.json

      - name: Get dependencies
        run: flutter pub get

      - name: Publish package
        run: flutter pub publish --force
