name: Github Release

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: Build Android Application
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4      
      
      - name: Check version increase (Pull Request)
        if: github.event_name == 'pull_request'
        uses: ./.github/workflows/check-pubspec-version.yml
        with:
          comparison_type: 'pr'

      - name: Check version increase (Push to main)
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: ./.github/workflows/check-pubspec-version.yml
        with:
          comparison_type: 'commit'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.13.9"
          channel: 'stable'
          cache: 'true'

      - name: Ensure pub-cache directory exists
        run: mkdir -p $HOME/.config/dart
      
      - name: Save credentials.json
        run: echo '${{ secrets.PUB_CREDENTIALS }}' > $HOME/.config/dart/pub-credentials.json

      # Opcional, mas recomendado para cobrir todas as bases:
      - name: Create legacy .pub-cache directory
        run: mkdir -p $HOME/.pub-cache

      - name: Write pub credentials to legacy path
        run: echo '${{ secrets.PUB_CREDENTIALS }}' > $HOME/.pub-cache/credentials.json

      - name: Get dependencies
        run: flutter pub get

      - name: Publish package
        run: flutter pub publish --force
      #  env:
       #   PUB_TOKEN: ${{ secrets.PUB_CREDENTIALS }} 

      
